### ISSUE TITLE
Netmap fails to compile external drivers on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jmtilli** [luigirizzo/netmap#480]
I installed Ubuntu 18.04 LTS, and installed the kernel headers and build tools there. Then I cloned netmap (git commit `22d5c46e4ee42f04db0d7d1b2ac7ff9e48811810`) and tried to run `./configure`. However, it fails to build the downloaded external drivers:

    ********************************** WARNING **********************************
    *** There were problems building the external driver e1000e.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling e1000e.
    *****************************************************************************
    ********************************** WARNING **********************************
    *** There were problems building the external driver igb.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling igb.
    *****************************************************************************
    ********************************** WARNING **********************************
    *** There were problems building the external driver ixgbe.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling ixgbe.
    *****************************************************************************
    ********************************** WARNING **********************************
    *** There were problems building the external driver ixgbevf.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling ixgbevf.
    *****************************************************************************
    ********************************** WARNING **********************************
    *** There were problems building the external driver i40e.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling i40e.
    *****************************************************************************
    ********************************** WARNING **********************************
    *** There were problems building the external driver mlx5.
    ***
    *** Please note that this is not related to the netmap patches,
    *** that were not applied.
    ***
    *** Disabling mlx5.
    *****************************************************************************

Attached is the config.log.
[config.log](https://github.com/luigirizzo/netmap/files/1958703/config.log)

Kernel version is:

    Linux bionic 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vmaffione** [comment]
As you can read in the log, this is not related to netmap. External drivers still don't build on 4.15. Either you wait that intel fixes the issue or you use the in kernel drivers from 4.15, which build correctly.

**Comment by jmtilli** [comment]
I guess it still needs netmap changes, because netmap fetches versions of those drivers that don't build...

Also, Intel has fixed the issue: https://sourceforge.net/projects/e1000/files/i40e%20stable/2.4.6/

    fix compilation error on kernel 4.15.1

So, it's a netmap issue after all... Netmap needs to download newer versions of the Intel drivers. Furthermore, the driver I'm most interested at the moment, mlx5, does not build with `--no-ext-drivers`. It says:

    ********************************** WARNING **********************************
    *** CONFIG_MLX5 not set in /lib/modules/4.15.0-20-generic/build/.config, skipping mlx5
    *****************************************************************************

...although I do indeed have `mlx5_core.ko` under `/lib/modules`.

**Comment by jmtilli** [comment]
About the MLX5: I have these in `/lib/modules/4.15.0-20-generic/build/.config`:

    CONFIG_MLX5_CORE=m
    CONFIG_MLX5_ACCEL=y
    CONFIG_MLX5_FPGA=y
    CONFIG_MLX5_CORE_EN=y
    CONFIG_MLX5_MPFS=y
    CONFIG_MLX5_ESWITCH=y
    CONFIG_MLX5_CORE_EN_DCB=y
    CONFIG_MLX5_CORE_IPOIB=y
    CONFIG_MLX5_EN_IPSEC=y

It's apparently looking at the wrong configuration option.

**Comment by giuseppelettieri** [comment]
There is a patch for i40e 2.4.6, it is just not the default since it is still untested. You can select it adding ```---select-version=i40e:2.4.6``` to your ```./configure```. 

As per mlx5, sorry, but the latest contribution was only for the external driver, and only for an old version of it, which does not compile on recent kernels.

**Comment by vmaffione** [comment]
The correct config entry for the mlx5 ethernet driver should be `CONFIG_MLX5_CORE_EN`, and not `CONFIG_MLX5`. That one is built in statically.
I just updated the code to handle this case, but for sure more work is still needed to let mlx5_en compile in recent kernels.

**Comment by vmaffione** [comment]
Is this fixed?

**Comment by jmtilli** [comment]
e1000e and ixgbevf still have issues, i40e, ixgbe, igb and virto_net apparently are built.

**Comment by arnavpisces** [comment]
Any fix yet for e1000e?

**Comment by vmaffione** [comment]
Is netmap configure reporting something like
````
********************************** WARNING **********************************
*** There were problems building the external driver e1000e.
***
*** Please note that this is not related to the netmap patches,
*** that were not applied.
***
*** Disabling e1000e.
*****************************************************************************
````
?
In that case there is nothing to fix on the netmap, but we need to wait that intel fixes the compilation on that particular kernel.

**Comment by giuseppelettieri** [comment]
There are a couple of more recent patches for e1000e in LINUX/final-patches, but they are not the default yet. If you are willing to do some testing, you can select them with '--select-version'. E.g.,

./configure --select-version=e1000e:3.4.2.1

**Comment by oPiZiL** [comment]
have you solved the problem?

**Comment by jmtilli** [comment]
There are still e1000e, ixgbevf and mlx5 issues.

**Comment by light-x** [comment]
I saw your config.log, the virto_net was not built, @jmtilli
