### ISSUE TITLE
Can't compile on SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

### ISSUE THREAD

**Issue by apofiget** [luigirizzo/netmap#386]
Hi there!
I've tried to compile Netmap on Debian9 system, but getting few errors.
It looks like:

> 
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:517:10: error: too few arguments to function ‘qdisc_drop’
>    return qdisc_drop(m, qdisc
>           ^~~~~~~~~~
> In file included from /usr/src/linux-headers-4.9.0-3-common/include/linux/filter.h:18:0,
>                  from /usr/src/linux-headers-4.9.0-3-common/include/net/sock.h:64,
>                  from /home/sphinx/projects/C/netmap/LINUX/bsd_glue.h:53,
>                  from /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:26:
> /usr/src/linux-headers-4.9.0-3-common/include/net/sch_generic.h:786:19: note: declared here
>  static inline int qdisc_drop(struct sk_buff *skb, struct Qdisc *sch,
>                    ^~~~~~~~~~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c: At top level:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:561:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>   .enqueue = generic_qdisc_enqueue,
>              ^~~~~~~~~~~~~~~~~~~~~
> 
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c: In function ‘linux_netmap_fault’:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:946:34: error: ‘struct vm_fault’ has no member named ‘vma’
>   struct vm_area_struct *vma = vmf->vma;
>                                   ^~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c: At top level:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:968:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>   .fault = linux_netmap_fault,
>            ^~~~~~~~~~~~~~~~~~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:968:11: note: (near initialization for ‘linux_netmap_mmap_ops.fault’)
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2164:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>   .ndo_get_stats64 = linux_nm_vi_get_stats,
>                      ^~~~~~~~~~~~~~~~~~~~~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2164:21: note: (near initialization for ‘nm_vi_ops.ndo_get_stats64’)
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c: In function ‘linux_nm_vi_setup’:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2178:5: error: ‘struct net_device’ has no member named ‘needs_free_netdev’
>   dev->needs_free_netdev = 1;
>      ^~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c: In function ‘nm_os_vi_persist’:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2203:47: error: macro "alloc_netdev" requires 4 arguments, but only 3 given
>   ifp = alloc_netdev(0, name, linux_nm_vi_setup);
>                                                ^
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2203:8: error: ‘alloc_netdev’ undeclared (first use in this function)
>   ifp = alloc_netdev(0, name, linux_nm_vi_setup);
>         ^~~~~~~~~~~~
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2203:8: note: each undeclared identifier is reported only once for each function it appears in
> At top level:
> /home/sphinx/projects/C/netmap/LINUX/netmap_linux.c:2169:1: warning: ‘linux_nm_vi_setup’ defined but not used [-Wunused-function]
>  linux_nm_vi_setup(struct ifnet *dev)
> 

GCC info:

> 
> gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 6.3.0 20170516 (Debian 6.3.0-18) 

Configuration script has been executed as:

> ./configure --disable-pipe --disable-vale --no-app --kernel-sources=/usr/src/linux-source-4.9/

Could you please help me? I've didn't find bug like that in project known issues.

**Comment by vmaffione** [comment]
This should be managed by the ./configure (e.g. we compile successfully on 4.13).
Can you retry with a a fresh clone of the netmap repo, with the latest code? Maybe your netmap build environment is messed up.

**Comment by apofiget** [comment]
Thanks, vmaffione! That helped me. For some reason my clone of sources has been corrupted.
