### ISSUE TITLE
netmap build fails on Ubuntu 16.04 LTS with kernel 4.10.0-32

### ISSUE THREAD

**Issue by jmtilli** [luigirizzo/netmap#356]
Netmap build fails on Ubuntu 16.04 LTS with kernel 4.10.0-32:

make -C /lib/modules/4.10.0-32-generic/build M=/home/juhis/netmap EXTRA_CFLAGS='-I/home/juhis/netmap -I/home/juhis/netmap/LINUX -I/home/juhis/netmap/LINUX/../sys -I/home/juhis/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-32-generic'
  CC [M]  /home/juhis/netmap/netmap_linux.o
/home/juhis/netmap/LINUX/netmap_linux.c:958:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .fault = linux_netmap_fault,
           ^
/home/juhis/netmap/LINUX/netmap_linux.c:958:11: note: (near initialization for ‘linux_netmap_mmap_ops.fault’)
/home/juhis/netmap/LINUX/netmap_linux.c:2154:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_get_stats64 = linux_nm_vi_get_stats,
                     ^
/home/juhis/netmap/LINUX/netmap_linux.c:2154:21: note: (near initialization for ‘nm_vi_ops.ndo_get_stats64’)
/home/juhis/netmap/LINUX/netmap_linux.c: In function ‘linux_nm_vi_setup’:
/home/juhis/netmap/LINUX/netmap_linux.c:2168:5: error: ‘struct net_device’ has no member named ‘needs_free_netdev’
  dev->needs_free_netdev = 1;
     ^
cc1: some warnings being treated as errors
/home/juhis/netmap/Kbuild:31: recipe for target '/home/juhis/netmap/netmap_linux.o' failed
make[2]: *** [/home/juhis/netmap/netmap_linux.o] Error 1
Makefile:1524: recipe for target '_module_/home/juhis/netmap' failed
make[1]: *** [_module_/home/juhis/netmap] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-32-generic'
netmap.mak:75: recipe for target 'netmap.ko' failed
make: *** [netmap.ko] Error 2

**Comment by vmaffione** [comment]
That's weird, it compiles ok on vanilla 4.10, 4.11 and 4.12.
How did you ./configure ?

**Comment by jmtilli** [comment]
This issue can be closed. I probably either did ./configure on the root directory (not LINUX), or alternatively had the clone in an erroneous state. I did "git clean -f; git clean -f -X" and re-did ./configure and make in the LINUX directory, and now it works.
