### ISSUE TITLE
build on linux 3.16 error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luigirizzo/netmap#20]
```
In file included from /home/sjp/env/c/push/netmap/LINUX/virtio_net.c:148:
/home/sjp/env/c/push/netmap/LINUX/virtio_netmap.h:180: error:
In function ‘virtio_netmap_free_rx_unused_bufs' ‘struct receive_queue' has 
no members
'num'


```

Original issue reported on code.google.com by `Shuang.J...@gmail.com` on 16 Sep 2014 at 3:07
