### ISSUE TITLE
igb-5.3.5.10 build error pci_enable_msix with kernel > 4.8 

### ISSUE THREAD

**Issue by michael2009** [luigirizzo/netmap#363]
Solved.

--- a/igb-5.3.5.10/src/kcompat.h        2017-09-07 14:36:09.497568602 +0800
+++ b/igb-5.3.5.10/src/kcompat.h        2017-09-07 14:36:34.509568599 +0800
@@ -5576,4 +5576,8 @@
 #define HAVE_PCI_ERROR_HANDLER_RESET_PREPARE
 #endif /* 4.13.0 */

+#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 8, 0)
+#define HAVE_PCI_ENABLE_MSIX
+#endif
+
 #endif /* _KCOMPAT_H_ */
--- a/igb-5.3.5.10/src/igb_main.c       2017-09-07 14:36:16.984568601 +0800
+++ b/igb-5.3.5.10/src/igb_main.c       2017-09-07 14:38:18.067568587 +0800
@@ -1047,8 +1047,15 @@
                        for (i = 0; i < numvecs; i++)
                                adapter->msix_entries[i].entry = i;

+#ifdef HAVE_PCI_ENABLE_MSIX
                        err = pci_enable_msix(pdev,
                                              adapter->msix_entries, numvecs);
+#else
+                       err = pci_enable_msix_range(pdev,
+                                       adapter->msix_entries,
+                                       numvecs,
+                                       numvecs);
+#endif
                        if (err == 0)
                                break;
                }

**Comment by giuseppelettieri** [comment]
Compilation succeeds with vanilla kernels, so that fix is likely to broke things for somebody else. What distribution are you using? Is it RedHat-based?

**Comment by michael2009** [comment]
Yes, vanilla kernel work . but ext_driver igb not work with kernel 4.9/4.10.11/4.13

**Comment by michael2009** [comment]
Because igb driver build failed with any kernel 4.9/4.10.11/4.13. not only issue for netmap .

**Comment by giuseppelettieri** [comment]
Sorry, I expressed myself badly. What I see on my test-bed is that the external, unpatched driver compiles fine on kernel.org kernels up to 4.11, while it fails on 4.12 and 4.13. If you are seeing compilation errors since 4.8 you must be using a non-vanilla kernel, i.e., a kernel that contains some vendor-specific patches. The version test on 4.8 is going to work for you, but break compilation for somebody else.

The problem should be notified to Intel, since it is unrelated to netmap, as you say.

**Comment by michael2009** [comment]
Yes , That's intel driver bug . Thanks .
