### ISSUE TITLE
examples/bridge broken on Windows platform

### ISSUE THREAD

**Issue by rincebrain** [luigirizzo/netmap#85]
(Windows 7 x64, VS2013)

I tried getting bridge.c working on Windows, and quickly ran into a problem with pb->nifp (and pb->mem) being 0x0 if you use something like:
bridge -i netmap:ethX
on Windows.

I tried the suggestion from #78 and changed the flags for pb to 0 instead of NM_OPEN_NO_MMAP, which got me a non-zero ->{mem,nifp}, but then I perpetually have no traffic crossing the interface as soon as I run bridge.exe until I kill it, presumably because the NIC is unhappy with my choices.

I even tried implementing a modification of bridge.c with select instead of poll, in a similar style to the -DBUSYWAIT flag available for pkt-gen, but still, no traffic.

I tried the code from #84, and it demonstrates the behavior the user reported - no traffic passing, periodically noticing packets, can't be ^C'd.

All I really want, at the moment, is to pass traffic into userspace and back out of the interface - once I've got that working, I'm sure I'll have a lot of fun extending the functionality.

**Comment by rincebrain** [comment]
Fascinatingly, it seems to be broken on Linux too with git HEAD.

I'm currently most of the way through a bisect...I'm doing a make clean under each of {examples,LINUX}, then a ./configure --no-drivers under LINUX, then a make, then a make under examples, load the netmap driver, and run bridge -v -i netmap:eth0 and see if it core dumps/seg faults/otherwise stops passing traffic

Current bisect log:
# good: [56082702c16a7c2ea8149bb84b9f56d210d162e9] fix FreeBSD compilation error
git bisect good 56082702c16a7c2ea8149bb84b9f56d210d162e9
# bad: [e06eac66db3abd214482969dfe683bd828ba6ab8] merge windows userspace code
git bisect bad e06eac66db3abd214482969dfe683bd828ba6ab8
# good: [d7f9b22e628c74b9b5f0a8eec812558dfd016cc5] [ptnetmap] cleanup ptnetmap code
git bisect good d7f9b22e628c74b9b5f0a8eec812558dfd016cc5
# good: [0c526c4f89a6c7e51d78e3dccce2e1c1a7fcc2ad] [ptnetmap] use ptnetmap_*sync() in if_lem
git bisect good 0c526c4f89a6c7e51d78e3dccce2e1c1a7fcc2ad
# skip: [d41d69fa53787e95eec7296cbd4e815ea1a7e8a0] remove unused functions
git bisect skip d41d69fa53787e95eec7296cbd4e815ea1a7e8a0
# skip: [8ab64d77b6c9f5865daabe340242a111c6ac0dd2] Merge remote-tracking branch 'origin/nm_os_send_up' enable batching towards the host stack
git bisect skip 8ab64d77b6c9f5865daabe340242a111c6ac0dd2
# bad: [f2ceae49d2a11aa3dfc9c1d30be4406c571bbbe7] ptnetmap: add comments for txsync()/rxsync()
git bisect bad f2ceae49d2a11aa3dfc9c1d30be4406c571bbbe7
# skip: [87cbb5ed3d558acd77a3c92a2989b8322cf25d4a] Merge remote-tracking branch 'origin/os-refactor'
git bisect skip 87cbb5ed3d558acd77a3c92a2989b8322cf25d4a
# skip: [9731bc7091c76b61486bb0a37611784736412f8b] start bringing in some windows-specific code
git bisect skip 9731bc7091c76b61486bb0a37611784736412f8b
# skip: [b7e588304066a1d95456dcbe046ca13c925d1bab] [ptnetmap] move ptnetmap_[tx|rx]sync() in ptnetmap.c
git bisect skip b7e588304066a1d95456dcbe046ca13c925d1bab
# good: [1729d70de5390998700c3aec834943d44a5c576f] linux: drop redefinitions of CURVNET* and cdev_*priv
git bisect good 1729d70de5390998700c3aec834943d44a5c576f
# skip: [702d9b008a55aefba531513aceedd6ee392e3bec] the good version is the one in windows-temp
git bisect skip 702d9b008a55aefba531513aceedd6ee392e3bec
# skip: [4fbbefe47c8ff02ba2a65e5360989468162cfcf4] more code normalization
git bisect skip 4fbbefe47c8ff02ba2a65e5360989468162cfcf4
# bad: [4679d68a07d17d836be57dacc03d196ae6a7206e] mark static variables as such to avoid missing declaration warnings
git bisect bad 4679d68a07d17d836be57dacc03d196ae6a7206e
# skip: [8c6d49abd21b7267a1939631345085fa7bd3640a] make DECLARE_SYSCTLS windows friendly
git bisect skip 8c6d49abd21b7267a1939631345085fa7bd3640a
# bad: [77f7d7bba589f65fe167b261fbe9dc11769895ff] add missing declarations for global variables
git bisect bad 77f7d7bba589f65fe167b261fbe9dc11769895ff

**Comment by rincebrain** [comment]
Hm, it seems that something in a range of commits where Linux building was broken is when this broke.

Let's see what we can find.

```
# good: [56082702c16a7c2ea8149bb84b9f56d210d162e9] fix FreeBSD compilation error
git bisect good 56082702c16a7c2ea8149bb84b9f56d210d162e9
# bad: [e06eac66db3abd214482969dfe683bd828ba6ab8] merge windows userspace code
git bisect bad e06eac66db3abd214482969dfe683bd828ba6ab8
# good: [d7f9b22e628c74b9b5f0a8eec812558dfd016cc5] [ptnetmap] cleanup ptnetmap code
git bisect good d7f9b22e628c74b9b5f0a8eec812558dfd016cc5
# good: [0c526c4f89a6c7e51d78e3dccce2e1c1a7fcc2ad] [ptnetmap] use ptnetmap_*sync() in if_lem
git bisect good 0c526c4f89a6c7e51d78e3dccce2e1c1a7fcc2ad
# skip: [d41d69fa53787e95eec7296cbd4e815ea1a7e8a0] remove unused functions
git bisect skip d41d69fa53787e95eec7296cbd4e815ea1a7e8a0
# skip: [8ab64d77b6c9f5865daabe340242a111c6ac0dd2] Merge remote-tracking branch 'origin/nm_os_send_up' enable batching towards the host stack
git bisect skip 8ab64d77b6c9f5865daabe340242a111c6ac0dd2
# bad: [f2ceae49d2a11aa3dfc9c1d30be4406c571bbbe7] ptnetmap: add comments for txsync()/rxsync()
git bisect bad f2ceae49d2a11aa3dfc9c1d30be4406c571bbbe7
# skip: [87cbb5ed3d558acd77a3c92a2989b8322cf25d4a] Merge remote-tracking branch 'origin/os-refactor'
git bisect skip 87cbb5ed3d558acd77a3c92a2989b8322cf25d4a
# skip: [9731bc7091c76b61486bb0a37611784736412f8b] start bringing in some windows-specific code
git bisect skip 9731bc7091c76b61486bb0a37611784736412f8b
# skip: [b7e588304066a1d95456dcbe046ca13c925d1bab] [ptnetmap] move ptnetmap_[tx|rx]sync() in ptnetmap.c
git bisect skip b7e588304066a1d95456dcbe046ca13c925d1bab
# good: [1729d70de5390998700c3aec834943d44a5c576f] linux: drop redefinitions of CURVNET* and cdev_*priv
git bisect good 1729d70de5390998700c3aec834943d44a5c576f
# skip: [702d9b008a55aefba531513aceedd6ee392e3bec] the good version is the one in windows-temp
git bisect skip 702d9b008a55aefba531513aceedd6ee392e3bec
# skip: [4fbbefe47c8ff02ba2a65e5360989468162cfcf4] more code normalization
git bisect skip 4fbbefe47c8ff02ba2a65e5360989468162cfcf4
# bad: [4679d68a07d17d836be57dacc03d196ae6a7206e] mark static variables as such to avoid missing declaration warnings
git bisect bad 4679d68a07d17d836be57dacc03d196ae6a7206e
# skip: [8c6d49abd21b7267a1939631345085fa7bd3640a] make DECLARE_SYSCTLS windows friendly
git bisect skip 8c6d49abd21b7267a1939631345085fa7bd3640a
# bad: [77f7d7bba589f65fe167b261fbe9dc11769895ff] add missing declarations for global variables
git bisect bad 77f7d7bba589f65fe167b261fbe9dc11769895ff
# bad: [25ec97316e12778292692927b756979e9bd4148f] fix nm_os_send_up() parameters for linux
git bisect bad 25ec97316e12778292692927b756979e9bd4148f
# skip: [f8a0214532662ba2186d6abc55497649b677508f] diff reduction with windows-temp
git bisect skip f8a0214532662ba2186d6abc55497649b677508f
# skip: [f52398513769269826f70ce8d87a8d2230304b5c] diff reduction with windows-temp
git bisect skip f52398513769269826f70ce8d87a8d2230304b5c
# skip: [5ee7f469b0b1608be50ba05addbd126398ff1e96] whitespace fixes
git bisect skip 5ee7f469b0b1608be50ba05addbd126398ff1e96
# skip: [03b70b47453c0d35be93a1a79409c7befe1cae39] add SYSBEGIN/SYSEND wrappers around sysctl variables. This may trigger -Wextra-semicolon warnings, will be fixed later.
git bisect skip 03b70b47453c0d35be93a1a79409c7befe1cae39
# skip: [844f8e1b71166becd68679e7af4fbe44cc3d3230] import a small change from master
git bisect skip 844f8e1b71166becd68679e7af4fbe44cc3d3230
# skip: [5880d4f17eb9bde094ae40476f00e757492525d3] whitespace cleanup
git bisect skip 5880d4f17eb9bde094ae40476f00e757492525d3
# skip: [a581278176d3e1bd8cb2911481914cc7954d0a87] whitespace removal
git bisect skip a581278176d3e1bd8cb2911481914cc7954d0a87
# good: [9cfd8fd9e722e84aec4dff37597b0fc2922e3b14] fix build for _WIN32 dependencies
git bisect good 9cfd8fd9e722e84aec4dff37597b0fc2922e3b14
# skip: [29a02c761988abe39cb1b6f71bd6e19d655d56d8] diff reduction with windows (whitespace)
git bisect skip 29a02c761988abe39cb1b6f71bd6e19d655d56d8
# skip: [ad692fa37b2cf36b8659dd7a561799ac06f906c1] add missing semicolon
git bisect skip ad692fa37b2cf36b8659dd7a561799ac06f906c1
# skip: [d416f9849af2772a2324b6ecd6608292849653c2] make NM_SEND_UP os-dependent
git bisect skip d416f9849af2772a2324b6ecd6608292849653c2
# only skipped commits left to test
# possible first bad commit: [25ec97316e12778292692927b756979e9bd4148f] fix nm_os_send_up() parameters for linux
# possible first bad commit: [ad692fa37b2cf36b8659dd7a561799ac06f906c1] add missing semicolon
# possible first bad commit: [29a02c761988abe39cb1b6f71bd6e19d655d56d8] diff reduction with windows (whitespace)
# possible first bad commit: [5ee7f469b0b1608be50ba05addbd126398ff1e96] whitespace fixes
# possible first bad commit: [844f8e1b71166becd68679e7af4fbe44cc3d3230] import a small change from master
# possible first bad commit: [702d9b008a55aefba531513aceedd6ee392e3bec] the good version is the one in windows-temp
# possible first bad commit: [8c6d49abd21b7267a1939631345085fa7bd3640a] make DECLARE_SYSCTLS windows friendly
# possible first bad commit: [03b70b47453c0d35be93a1a79409c7befe1cae39] add SYSBEGIN/SYSEND wrappers around sysctl variables. This may trigger -Wextra-semicolon warnings, will be fixed later.
# possible first bad commit: [4fbbefe47c8ff02ba2a65e5360989468162cfcf4] more code normalization
# possible first bad commit: [f52398513769269826f70ce8d87a8d2230304b5c] diff reduction with windows-temp
# possible first bad commit: [f8a0214532662ba2186d6abc55497649b677508f] diff reduction with windows-temp
# possible first bad commit: [8ab64d77b6c9f5865daabe340242a111c6ac0dd2] Merge remote-tracking branch 'origin/nm_os_send_up' enable batching towards the host stack
# possible first bad commit: [d41d69fa53787e95eec7296cbd4e815ea1a7e8a0] remove unused functions
# possible first bad commit: [5880d4f17eb9bde094ae40476f00e757492525d3] whitespace cleanup
# possible first bad commit: [d416f9849af2772a2324b6ecd6608292849653c2] make NM_SEND_UP os-dependent
```

**Comment by rincebrain** [comment]
Okay, so the segfaulting on Linux for bridge.c with that incantation is just a side effect of needing the change from #78.

So this works fine on Linux now, but not on Windows. Lovely.

**Comment by Alessio-Faina** [comment]
Hello rincebrain, a fix will be available soon but it will work in busywait mode only; at the moment the poll mechanism under Windows doesn't supports multiple file descriptors and the bridge application needs this type of mechanism.
Using "make _apps" under WINDOWS directory will generate the bridge-b application, this new executable should work as expected, anyway let me know if there are other problems.

**Comment by rincebrain** [comment]
Hi @Alessio-Faina,
So, is there any way you could point me toward where the underlying problem is for this issue, if you don't already have a fix available; I'm currently evaluating using netmap for a project and I've been trying to debug this myself, but I obviously have less familiarity with the codebase so far.

**Comment by giuseppelettieri** [comment]
I have pushed the busy wait workaround mentioned by Alessio, in case you want to experiment with it.

**Comment by rincebrain** [comment]
Nope, bridge-b definitely still causes all traffic to be dropped while it's running, both in a VM and on my physical testbed, both running Win7 x64 Pro.

(I'll have more information once I re-enable DbgPrint at a nonzero level on this testbed and have a debugger attached; I had it disabled while trying to debug serial console windbg issues)

**Comment by rincebrain** [comment]
I'm guessing it's something silly, but I haven't figured out what yet from reading the code.

@Alessio-Faina I'm curious what hardware/VM environment you're testing on?

dbgprint output with verbosity 0x8 from loading and then just trying to ping an IP on my physical Win7 host follows.

NETMAP.SYS: Driver loaded at address 0xFFFFF880031AF9B0 
netmap: loaded module
*** Global Sysctl Table entries = 14, total size = 604 ***
*** GST[0]: dev.netmap.verbose
*** GST[1]: dev.netmap.no_timestamp
*** GST[2]: dev.netmap.mitigate
*** GST[3]: dev.netmap.no_pendintr
*** GST[4]: dev.netmap.txsync_retry
*** GST[5]: dev.netmap.adaptive_io
*** GST[6]: dev.netmap.flags
*** GST[7]: dev.netmap.fwd
*** GST[8]: dev.netmap.admode
*** GST[9]: dev.netmap.generic_mit
*** GST[10]: dev.netmap.generic_ringsize
*** GST[11]: dev.netmap.generic_rings
*** GST[12]: dev.netmap.default_pipes
*** GST[13]: dev.netmap.bridge_batch
In WM_DEVICECHANGEIn WM_DEVICECHANGEWM_DEVICECHANGE KillTimer(1012e, 0).
hkcmd ---In WM_DEVICECHANGEhkcmd ---TVwizard not Enabled439.768357 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

NDISLWF: <===DriverEntry, Status =        0
Fail to read system\currentcontrolset\services\Lmhosts\Parameters\EnableUserMode, error=2
445.368766 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

445.384366 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

445.394874 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

Netmap.sys: NIOCREGIF
Netmap.sys: Requested interface ifIndex: 11
pfilter FFFFFA80045B0CB0 refcount 1
445.977167 [2005] netmap_do_regif           lut FFFFFA8005E6E000 bufs 163840 size 2048
unimplemented FFFFFA800521C190 idx 0 na FFFFFA80044C48E0
Netmap.sys: NETMAP_MMAP
Netmap.sys: Memory allocated to user process
446.055168 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

446.070768 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

446.081239 [  93] ioctlCreate               Netmap.sys: ioctlCreate::priv->np_refcount = 1

Netmap.sys: NIOCREGIF
Netmap.sys: Requested interface ifIndex: 11
pfilter FFFFFA80045B0CB0 refcount 2
446.117568 [2005] netmap_do_regif           lut FFFFFA8005E6E000 bufs 163840 size 2048
unimplemented FFFFFA80057989C0 idx 0 na FFFFFA800DC21DF0
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active
unimplemented FFFFFA80057989C0 - nm_os_mitigation_active

**Comment by vmaffione** [comment]
Is the problem still there?
